//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xPenEntities : DbContext
    {
        public xPenEntities()
            : base("name=xPenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IESCollege> IESColleges { get; set; }
        public virtual DbSet<IESSem> IESSems { get; set; }
        public virtual DbSet<IESStream> IESStreams { get; set; }
        public virtual DbSet<IESUniversity> IESUniversities { get; set; }
        public virtual DbSet<IESUserProfile> IESUserProfiles { get; set; }
        public virtual DbSet<iesViewUserProfile> iesViewUserProfiles { get; set; }
        public virtual DbSet<IESObjectiveQuestion> IESObjectiveQuestions { get; set; }
        public virtual DbSet<IESObjectiveTest> IESObjectiveTests { get; set; }
        public virtual DbSet<IESSubjectiveTest> IESSubjectiveTests { get; set; }
        public virtual DbSet<IESTestPaperInventory> IESTestPaperInventories { get; set; }
        public virtual DbSet<IESSubjectiveQuestion> IESSubjectiveQuestions { get; set; }
    }
}
