//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IESObjectiveTest
    {
        public int QPaperID { get; set; }
        public Nullable<int> UnivID { get; set; }
        public Nullable<int> StreamID { get; set; }
        public Nullable<int> SemId { get; set; }
        public int QuestionID { get; set; }
    }
}
