//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IESOrderTransaction
    {
        public int TransactionID { get; set; }
        public int OrderID { get; set; }
        public string Key { get; set; }
        public int Status { get; set; }
        public System.DateTime TransactionDate { get; set; }
    }
}
