//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IESPaper_Question
    {
        public int PaperQuestionID { get; set; }
        public int PaperID { get; set; }
        public int QuesID { get; set; }
    }
}
