//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IESQuestion
    {
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public string Solution { get; set; }
        public int SubjectID { get; set; }
        public int TopicID { get; set; }
        public int DifficultyLevel { get; set; }
    }
}
