//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IESSubjectiveQuestion
    {
        public int QuesID { get; set; }
        public string Question { get; set; }
        public string answer { get; set; }
        public int C_SubjectID_ { get; set; }
        public int SemID { get; set; }
    }
}
