//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class iesViewUserProfile
    {
        public int UserID { get; set; }
        public string Token { get; set; }
        public string Email { get; set; }
        public int UnivID { get; set; }
        public string Name { get; set; }
        public int CollegeID { get; set; }
        public string College_Name { get; set; }
        public string Stream_Name { get; set; }
        public int StreamID { get; set; }
        public int SemesterID { get; set; }
        public string Sem_Name { get; set; }
        public int Status { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public System.DateTime DisableDate { get; set; }
    }
}
