//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewIESQuestionPaper
    {
        public int PaperID { get; set; }
        public int Year { get; set; }
        public int Cost { get; set; }
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> Unit { get; set; }
        public int CollegeID { get; set; }
        public string CollegeName { get; set; }
        public Nullable<int> UnivID { get; set; }
        public string UniversityName { get; set; }
        public int StreamID { get; set; }
        public string StreamName { get; set; }
        public int SemID { get; set; }
        public string SemesterName { get; set; }
    }
}
