//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewIESAcademicProfile
    {
        public int ProfileID { get; set; }
        public int UserID { get; set; }
        public string UNIVID { get; set; }
        public string UNIVERSITYNAME { get; set; }
        public int CollegeID { get; set; }
        public string CollegeName { get; set; }
        public int StreamID { get; set; }
        public string StreamName { get; set; }
        public int SemesterID { get; set; }
        public string SemesterName { get; set; }
    }
}
