//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewIESSubject
    {
        public int ClassSubID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> CollegeID { get; set; }
        public Nullable<int> StreamID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string SubjectName { get; set; }
    }
}
