//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IESMater_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewIESPaperQuestion
    {
        public int PaperQuestionID { get; set; }
        public int PaperID { get; set; }
        public int QuesID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> CollegeID { get; set; }
        public Nullable<int> StreamID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> SemID { get; set; }
        public Nullable<int> Year { get; set; }
        public string Question { get; set; }
        public string Solution { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> DifficultyLevel { get; set; }
    }
}
